### ISSUE TITLE
[REQUEST] Umatrix add-on dull colors

### ISSUE THREAD

**Issue by rawlife56** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#100]
In Umatrix addon, colors are pretty dull and hard to see the text over it, can you please bump them up a little brighter ?

Ublock is perfect in this regard and I guess you can just copy the same colors over with minor tweaks. I tried to do it but the changes weren't taking effect.

**Comment by Izheil** [comment]
I updated it so that colors are more visible and text has more contrast against the background. See if it's better now.
![Umatrix Popup](https://user-images.githubusercontent.com/33794458/102000280-3be5e980-3ce6-11eb-8467-76883f9ebc9c.png)
