### ISSUE TITLE
[BUG] TCL Panel doesn't fit on 1024*768 screen

### ISSUE THREAD

**Issue by candelab** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#103]
**Describe the bug**
TCL Panel doesn't fit on 1024*768 screen, needs scroll bar or something to reach "Patch" button.

**Comment by candelab** [comment]
Also if you do the manual install, what files do you edit to set the number of tab rows? Thanks for the great stuff!

**Comment by Izheil** [comment]
A 1024x768 screen is quite small for today standards, and a new patcher (which will be smaller) is under construction, so nowadays the only changes to the old patcher will just be compatibility fixes for the functions. 

You can do the [manual install](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/tree/master/Multirow%20and%20other%20functions/JS%20Loader) meanwhile, or use the tab key to cycle through the elements until you can press the patch button.

> Also if you do the manual install, what files do you edit to set the number of tab rows? Thanks for the great stuff!

That would be on the [Multirow tab files](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/tree/master/Multirow%20and%20other%20functions/Multirow%20tabs). You just need to edit the variables on the editable area near the top of the script, or in this case `--max-tab-rows` inside `MultiRowTab-scrollable.uc.js`.

For other functions, you can get them from the [other features folder](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/tree/master/Multirow%20and%20other%20functions/Other%20features), or pasting anything you like from the [css tweaks folders](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/tree/master/CSS%20tweaks) to your [userChrome.css](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/wiki/Editting-CSS-files) file.

**Comment by Izheil** [comment]
I forgot to mention that there is also [console command support](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/wiki/Installer-console-commands), so even if it's too big to fit on screen right now until the new mayor version, you can also install things using the installer from the terminal following the directions from the wiki.
