### ISSUE TITLE
[BUG] Win installer/app not working on win7

### ISSUE THREAD

**Issue by kenpoole** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#105]
**Describe the bug**
When on my win7 box  I run the windows installer, i get an eror "The programcan't start because api-ms-win-core-path-i1-1-0.dll is missing ..."

**To Reproduce**
download 1.7.10 windows installer onto win7 box
run installer - see above error

**Expected behavior**
the installer to work like it did on my win10 box

**Screenshots**
unable to add screen snapshot

**Desktop (please complete the following information):**
 - OS: win7
 - VersionFF 84.0.2

**Comment by Izheil** [comment]
That's more related to some corrupt/missing dll on your system.

Try downloading the dll from [here](https://www.dll-files.com/api-ms-win-core-path-l1-1-0.dll.html), unzip it (I am not sure if Windows 7 has a built-in uncompressor like Windows 10, but if it doesn't, try using a program like [7-zip](https://www.7-zip.org/) for that) and place the dll inside your Windows 7 `C:\Windows\SysWOW64` folder, or inside the `C:\Windows\System32` one if the SysWow64 doesn't exist (if it asks to overwrite anything, make a backup of the file it wants to overwrite before overwritting).

After that, restart and try again.

**Comment by kenpoole** [comment]
worked - thanks

**Comment by goonis** [comment]
It's not corrupt/missing dll issue.
Problem is you compile your application for Windows under Python 3.9, but last version of Python supported in Windows 7 is 3.8.6.
You can find on-topic discussion, for example, [here](https://github.com/blackjack4494/yt-dlc/issues/77) 

BTW, downloading dll from [here](https://www.dll-files.com/api-ms-win-core-path-l1-1-0.dll.html) (both available versions) not working for me, Win7 x64, Multirow-Patcher-Quantum-Nox-Installer-Windows-1.7.10.exe dies on start with "Multirow-Patcher-Quantum-Nox-Installer-Windows-1.7.10.exe has stopped working".

So, if you want support Windows 7 despite OS EOL in Jan,2020 you need compile your application against Python 3.8.6, not 3.9.

**Comment by Izheil** [comment]
Anyone using an EOL OS should expect these kind of uncompatibilities. Just like I didn't know that it was an issue with the newer python version, this will be likely to happen with other more mainstream software where their developers will just not care.

With that said, I recompiled with 3.8.6 to add support to Windows 7 again on version [1.7.10-rev1](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/releases/download/FF84/Multirow-Patcher-Quantum-Nox-Installer-Windows-1.7.10-rev1.exe), but anyone using Windows 7 should consider updating at some point in the near future not only to avoid issues like this, but with other software in the future.
