### ISSUE TITLE
[BUG] uBlock Origin Theme - Text hard to read

### ISSUE THREAD

**Issue by RandyJackson59** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#108]
Hi
The Colors of the theme for the uBlock Origin Control Panel make it hard to read the text

I made a Screenshot how it looks so you can see: https://imgur.com/a/GGPnISq
The right side is fine, but the left side is a little hard to read as you can see

 - OS: Windows 10 x64
 - Version 85

Unfortunately i don't know how  to change the colors myself, i'd appreciate if you can tell me, or change it in your files.
Thank you

**Comment by Izheil** [comment]
I updated the theme. 
I had misplaced some lines last time that I updated it. It should be fine now.

**Comment by RandyJackson59** [comment]
Wow that was fast!
Thank you so much, i really appreciate your work and your help.
