### ISSUE TITLE
[BUG] new tab button may fall into a new row alone

### ISSUE THREAD

**Issue by Merci-chao** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#109]
This code will fix the problem.
`#tabs-newtab-button {
	margin-left: -32px !important;
}
.tabbrowser-tab:last-of-type {
	margin-right: 32px !important;
}`

**Comment by Izheil** [comment]
Thanks, added your code to all multirow versions. I'll upload the updated installers in a while and then close this.

**Comment by Izheil** [comment]
I uploaded the fix on v1.7.11.
