### ISSUE TITLE
[BUG] moving mutiple selected tabs

### ISSUE THREAD

**Issue by Merci-chao** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#111]
1. Use Ctrl + Click to select multiple tabs on different rows:
![圖片](https://user-images.githubusercontent.com/18614572/107728830-1d25c280-6d2a-11eb-9637-2cb9436554e4.png)
2. Drag to move them,  some other tabs are shifted wrongly:
![圖片](https://user-images.githubusercontent.com/18614572/107728880-3d558180-6d2a-11eb-9f55-8d5d72e7caf6.png)
3. After dropping them, the tabs are not placed together:
![圖片](https://user-images.githubusercontent.com/18614572/107728947-683fd580-6d2a-11eb-9592-372463dde736.png)

I've added some lines of code to fix:
[MultiRowTab-scrollable.uc.txt](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/files/5969628/MultiRowTab-scrollable.uc.txt)

The code added in ondragstart is for matching the original behavior of Firefox, tabs are grouped when you start dragging.

**Comment by Izheil** [comment]
Thanks, great addition!
I don't usually reorder multiple tabs, so I never noticed.
Just updated multirow files with your fix.

**Comment by Izheil** [comment]
Added this to v1.7.12 of the installer.
