### ISSUE TITLE
Bitdefender - Multirow-Patcher-Quantum-Nox-Installer-Windows-1.5.1.exe is malware of type Gen:Variant.Bulz.382815

### ISSUE THREAD

**Issue by Wolvverine** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#113]
Multirow-Patcher-Quantum-Nox-Installer-Windows-1.5.1.exe is malware of type Gen:Variant.Bulz.382815

**Comment by Izheil** [comment]
See issue #54. 
Python binaries created with pyinstaller are detected by many AV's no matter what code you put in the program (and the issue was already mitigated on 1.7.5 onwards).
