### ISSUE TITLE
[BUG] The first few rows did not show up on Firefox 88

### ISSUE THREAD

**Issue by tungmilan** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#117]
**Describe the bug**
Firefox updated to version 88.0 and suddenly I couldn't see or click on any tab on the first few rows. I could use `Ctrl + Pg Up` or `Pg Down` to navigate through these tabs but not the mouse.

Can you please help? Thanks!

**To Reproduce**
Steps to reproduce the behavior, or a brief explanation on it:
1. Open Firefox 88 at maximized windows size
2. Open many tabs 

**Expected behavior**
All tabs are visible

**Screenshots**
![firefox_2021-04-25_22-18-23](https://user-images.githubusercontent.com/6590141/116032993-7147ff80-a615-11eb-8438-5f720bfa5452.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 88.0

**Additional information**
I used the files in this folder `Installers\Multirow & other functions`
- Copy  `utils` folder and `MultiRowTab-scrollable.uc.js` file to `chrome` folder (`AppData\Roaming\Mozilla\Firefox\Profiles`)
- Copy `defaults` and `config.js` to `C:\Program Files\Mozilla Firefox`

**Comment by Izheil** [comment]
I can't seem to replicate the issue on your same OS and FF version, do you have any other Multirow version inside your `chrome` folder?

If so try removing the old one, and just leave one of the multirow versions.

Also make sure that you don't have any code on `userChrome.css` that could be interfering with tabs.

**Comment by tungmilan** [comment]
Thank you! Works again after doing what you suggested and restarting Firefox!
