### ISSUE TITLE
[BUG] Show more bookmarks arrow popup not themed

### ISSUE THREAD

**Issue by maxfun03** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#118]
When I open Show More Bookmarks the background color seems unchanged to the original.

**Comment by Izheil** [comment]
Should be fixed with [this commit](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/commit/f964fbcc0bbff9d727401212339f8506943ae037) now.

**Comment by maxfun03** [comment]
Thanks for the fast response that fixed it.

**Comment by AuRiMaS666** [comment]
Subfolders are still white for me.

![2021-04-29_18-12-35](https://user-images.githubusercontent.com/59185222/116575585-72c83f00-a917-11eb-894e-fb1aca29a223.png)

**Comment by Izheil** [comment]
The white folders should be fixed on [this commit](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/commit/26f6c74062d487b3851fd8dddefbb5f2631effa0).
