### ISSUE TITLE
[BUG] Multi-row not working with Ubuntu Mate (20.04)

### ISSUE THREAD

**Issue by bitbooster** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#119]
**Describe the bug**
Trying to apply the patch for multi-row doesn't work on Ubuntu Mate 20.04 (while on Ubuntu 'plain' does)

**To Reproduce**
On a freshly installed VM with Ubuntu Mate 20.04 :
- launch Firefox once
- download the installer Multirow-Patcher-Quantum-Nox-Installer-Linux-1.7.13.elf
- in about:config set toolkit.legacyUserProfileCustomizations.stylesheets to true
- close Firefox
- run Multirow-Patcher-Quantum-Nox-Installer-Linux-1.7.13.elf
- tick only on "Multi-row patch", and click Patch
- launch Firefox again
- open 20 tabs and notice how it they are added to the same scrollable line

**Expected behavior**
- opening many tabs they are arranged in a multi-row fashion (as it happens with plain Ubuntu)

**Additional information**
It seems the cause for this behavior is a Ubuntu Mate customization provided by the package `ubuntu-mate-default-settings` that regarding Firefox basically adds (so far) only a customized homedir. 
This is done by adding two files:
- `/usr/lib/firefox/defaults/prefs/all-ubuntumate.js` which has the following two lines:
```
pref("general.config.obscure_value", 0);
pref("general.config.filename", "ubuntumate.cfg");
```
- `/usr/lib/firefox/ubuntumate.cfg` which contains:
```
//
defaultPref("browser.startup.homepage", "https://start.ubuntu-mate.org");
```
Removing these two files seems to be enough to allow the multi-row patch to work.

**Comment by Izheil** [comment]
Looks like a specific issue of that distribution (and possibly of other distributions that may do the same).

I'd rather not remove those files automatically with the installer (someone might have changed them manually, and would not like that they got randomly removed to override their settings).

What can be done would be alerting the user that other configuration files exist, and then telling them the possibly conflictive files.
In case it's just 1 non-standard .js and .cfg, we could prompt to remove them or keep them.

**Comment by bitbooster** [comment]
Agree.
Maybe you can also collect in a section of the wiki these kind of 3rd party compatibilities.
I opened the issue mostly to document it, so you can close it if you want.

**Comment by Izheil** [comment]
Yeah, I'll add it to the wiki, thanks for reporting it.
