### ISSUE TITLE
[BUG] On Linux using the Tabs-below-as.css results in a unreadable titlebar.

### ISSUE THREAD

**Issue by TheReptile** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#120]
**Describe the bug**
When I install the Tabs-below-as.css tweak, the titlebar is not themed anymore on Linux.

**To Reproduce**
Steps to reproduce the behavior, or a brief explanation on it:
1. Install the Tabs-below-as.css tweak
2. Activate the builtin Dark theme
3. The titlebar is now not themed anymore.

**Screenshots**

Dark Theme without Tabs-below-as.css
![image](https://user-images.githubusercontent.com/22954131/120294993-0601e500-c2c7-11eb-94d5-2695b17cfce8.png)

Dark Theme with Tabs-below-as.css
![image](https://user-images.githubusercontent.com/22954131/120294737-ca671b00-c2c6-11eb-9a0e-1e465e2743c0.png)

**Desktop (please complete the following information):**
 - OS: Linux Mint 20.1
 - Version FF 88.0.1

**Additional information**
This issue doesn't happen on Windows 10 with the same tweak.

**Comment by Izheil** [comment]
Seems like an issue with your OS GTK theme, since for me it works as it should.
![titlebar](https://user-images.githubusercontent.com/33794458/120359533-10909e80-c308-11eb-9838-ee2ae03d0b3f.png)

You can try manually painting the `#toolbar-menubar` on dark themes adding this code to your `tabs-below.as.css` file, or to your `userChrome.css`:

```
#toolbar-menubar[brighttext] {
    background-color: #000 !important
}
```

**Comment by TheReptile** [comment]
Weird, it seemed to happen after a Firefox upgrade, I think 87 -> 88, but I'm not completely sure.
Your workaround works fine for me, but only when I use it in the `tabs-below.as.css` file. 

Thanks again!

**Comment by TheReptile** [comment]
Hmmm, on my Windows 10 machine I just got an update to FF 89.0. Now the same issue occurs there. 
But the workaround also works there :)

**Comment by Izheil** [comment]
You are right, I can replicate it on Windows 10 after the proton update.
I [fixed the color issue and also resized the tab bar to fit the new sized tabs from Proton](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/commit/a0c2f10c07adb91f0dd2482b31057e113131caa1), so it should work now!
