### ISSUE TITLE
[BUG] uBlock Origin's Element Picker UI

### ISSUE THREAD

**Issue by Elaborendum** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#129]
**Describe the bug**
uBO's element picker UI is mostly white, except for the area describing which element is being selected.

**To Reproduce**
1. Go to any page
2. Click on uBlock Origin, click on the element picker
3. Pick any element on the page
4. See mostly white popup

**Screenshots**

![imagen](https://user-images.githubusercontent.com/71190696/126078944-fd00a71c-ed9b-4f3f-87cf-f80ea47f96a9.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Firefox 90.0

**Additional information**
Is this just the inevitable result of the fix for #8?

**Comment by Izheil** [comment]
The code was split on userContent, since addons.css didn't use to be its own file a long time ago, and it required a global scope to work.

I just merged the code to `addons.css`, and should be work as a standalone without userContent from here.
