### ISSUE TITLE
[BUG] Some colors in Firefox Account make some text hard to read

### ISSUE THREAD

**Issue by Elaborendum** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#130]
**Describe the bug**
When going to accounts.firefox.com/settings, the page's header is white, along with some main options, while their text is light gray, making it all hard to read. This also happens with the dropdown menu that appears when you click the 9 squares button on the top right, next to the profile picture.

Meanwhile, accounts.firefox.com/signin has the inverse problem, the background is fully dark, but some text remains dark (particularly noticeable is the email), making some of it hard to read.

**To Reproduce**
1. Go to accounts.firefox.com/settings and accounts.firefox.com/signin
2. See error

**Screenshots**

![imagen](https://user-images.githubusercontent.com/71190696/126586367-56259b43-a586-4630-a4d9-c70ccfb9eb48.png)

I can't show the /singin because the main problem is the email, and, well.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Firefox 90.0.1

**Comment by Izheil** [comment]
Thanks for reporting it!
The issue should be now solved on `userContent.css` with [this commit](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/commit/0cda322e8cdc7322853af5b5ca42afe7e1f0fdf4).
