### ISSUE TITLE
[REQUEST] Support LibreWolf (in Addons UUID replacer)

### ISSUE THREAD

**Issue by Mayurifag** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#131]
Thanks for your work! 

**Is your feature request related to a problem? Please describe.**
It seems, Addons UUID replacer doesn't know about `~/.librewolf` folder, so it cant be used by librewolf browser users.

**Describe the solution you'd like**
Addons UUID replacer should be added with yet another folder to look for profiles.

**Describe alternatives you've considered**
As an alternative, Addons UUID replacer may have option to set the folder to update manually. This way seems to be more inclusive: not only the librewolf users may have benefits, but also portable firefox users (with not default user folder) or any other firefox-based browser users.

I didn't look too much at source code, probably there is a way for single use fast monkey-patch if I search for `/.mozilla` and change it to `/.librewolf`

**Comment by Izheil** [comment]
Sounds like a good idea. I'll add a third option to add a custom location on where to install it when I have some time to work on this.

**Comment by Izheil** [comment]
Should be working now on [1.2.0](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/releases/tag/1.2.0)!

**Comment by Mayurifag** [comment]
Sounds great, thanks a lot for your job done on this topic! 

Sorry, can't check the solution for some time, because I have already monkey-patched and made working my librewolf profile 😋 

I guess its better to close the issue now, thank you one more time 👍🏻
