### ISSUE TITLE
[BUG] Multirows doesn't work well with Firefox 91.0

### ISSUE THREAD

**Issue by hicks0r** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#134]
Multirows doesn't work well with Firefox 91.0
![2021-08-18 23_10_00-New Issue · Izheil_Quantum-Nox-Firefox-Dark-Full-Theme](https://user-images.githubusercontent.com/89164669/129972722-0220e47e-237a-4bc7-b505-f75699772149.png)

**Comment by Izheil** [comment]
Should be fixed now with [the lastest commit](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/commit/65106c938796cd8f7852bcc3bc5e7821f6d4b2f9).
