### ISSUE TITLE
Scrollbar is always displayed on Multirow tabs

### ISSUE THREAD

**Issue by Aushilfsarnie** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#136]
Hello. Thank you for the great package!
When using the MultiRowTab-scrollable.uc.js, the scroll bar is always displayed (from the first row). Is it possible to hide it until the --max-tab-rows are reached? Thanks in advance

**Comment by Izheil** [comment]
It shouldn't show until the --max-tab-rows variable value of rows is reached already.
Do you have any other code that affects the toolbars, or have you changed any other value apart from that variable on the file?

**Comment by Aushilfsarnie** [comment]
Thank you for help and sorry for my question. You're right. It was my mistake...

**Comment by Izheil** [comment]
It's alright, we all make mistakes.
Since you got it working I'll close this then.
