### ISSUE TITLE
[BUG] Multirow tabs not working in FF92

### ISSUE THREAD

**Issue by tanis138** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#139]
Hi! 
I'm using only multirow tabs feature in my FF. I've installed JS loader + MultiRowTab-scrollable-autohide.uc.js according to the instruction. And it was working up to FF 91.0.1
Today I've updated my FF to 92 and multirow tabs stopped working. All tabs are alligned in one row. 
Had to downgrade FF to 91.0.1 Tested on W7 and W10.

FF92 W7 (on W10 same situation):
![FF](https://user-images.githubusercontent.com/42606462/132829756-1ce18dcb-47f9-455b-8eb2-e3748a1b1fbf.png)

FF91 W10 (on W7 same situation):
![FF91](https://user-images.githubusercontent.com/42606462/132830109-a763e6b1-bc61-4718-8936-745c066aeff3.jpg)

**Comment by Izheil** [comment]
Hello,
Do you have any other .js files on your chrome folder or any other code on userChrome.css?
If so, test multirow without any of those, (so only having the `/utils` folder and multirow on your chrome folder) and see if it works with just that.

On W10 and FF92 all multirow versions are working for me, so they should also work for you.
![92](https://user-images.githubusercontent.com/33794458/132690250-7cf364b5-5868-4774-872c-fc804a7bfc0b.png)

**Comment by tanis138** [comment]
Inside my chrome folder I have only  MultiRowTab-scrollable-autohide.uc.js (10/09/2021 09:49) and utils folder from the JS loader. I dont't have userChrome.css at all. It's strange, that multirows became broken only after update to 92. When I manually downgraded to 91, tabs became multirow again.
Tried to restart browser in safe mode - didn't help.

**Comment by tanis138** [comment]
Hm! Very interesting. I've created new profile in about:profiles and restarted browser. Multirow tabs started to work on new profile. Then, I've selected back my old profile and restarted the browser - and multirow tabs magically start to work.
Thank you for help!

**Comment by petacz** [comment]
I had the same issue.
I had to restart Firefox in Troubleshoot mode and then normally.
It seems there is some caching involved.

**Comment by Izheil** [comment]
I had someone else with the same issue on reddit and clearing the startupCache folder didn't seem to help him (You can access it to clear it on about:profiles -> Open local profile folder), but reinstalling both Firefox and the profile seemed to help him.

The best way so far seems to be restarting on troubleshoot, and changing to a different profile and then back. The key is changing to a different profile, and possibly clearing the cache mentioned before, but I'm not sure which one fixes it exactly, since each of those by themselves didn't work out of the box.

**Comment by caramboleyo** [comment]
In my case it helped to remove the ~/.cache/mozilla folder, then even the tab layout changed.
FF92 on Ubuntu20.04
