### ISSUE TITLE
FF92 - Can't get Multirow Tabs working

### ISSUE THREAD

**Issue by galapogos01** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#141]
**Describe the bug**
FF92 - Can't get Multirow Tabs working.

**To Reproduce**
Steps to reproduce the behavior, or a brief explanation on it:
1. Have had a working setup for years
2. FF92 update installed
3. No more multi row tabs.

**Expected behavior**
Multirow tabs works :)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Version FF92 x64

**Additional information**
Have tried updating MultiRowTab-scrollable.uc.js, manually reinstalling JS Loader, and even using the patcher. Even test.as.css does not work so I am assuming it's a JS Loader issue.

**Comment by Izheil** [comment]
Please see [#139](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/issues/139) for the known fixes.
So far we don't know why some people are having trouble with external js files on FF92 but others don't, but the steps to get it working seem to be somewhat related to some kind of caching.

Try:
 1. Close Firefox and delete startupCache folder contents (you can access it on about:profiles -> Local folder directory of your used profile).
 2. Start Firefox on safe mode and then back to normal mode.
 3. Try starting Firefox from a different profile and then go back to the one you were using.

Those 3 seem to fix the issue for some people, although you may need to do all of those for it to work.

**Comment by galapogos01** [comment]
Thank you so much for the quick response @Izheil ! Safe mode restart then back to normal mode fixed it for me. I wasted so much time on this! Maybe a note in the version history comments of multirow tabs?

**Comment by Izheil** [comment]
No problem.
Sadly the issue is global for all .js files, not just for multirow. Someone that was using tabs-on-hover would encounter the same problem.

As for the troubleshooting note on the releases page, there is already a troubleshooting note there linking to the troubleshooting wiki to solve these issues. I updated the troubleshooting wiki page with the [steps proposed](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/wiki/Troubleshooting#some-function-stopped-working-after-the-lastest-firefox-update) here for other users.

**Comment by bparees** [comment]
Not super likely to be the cause of other people's issues, but I found that I had to refresh the files in my `$profile/chrome/utils` dir from:
https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/tree/master/Multirow%20and%20other%20functions/JS%20Loader/utils

Apparently mine were somewhat stale, but had been working fine up through FF91.  I tried all the other procedures listed here w/ no effect, but once I updated those files and cleared the startupCache folder, it's working again.  Given how infrequently they change, maybe some other people are in the same situation of not having checked/updated them.
