### ISSUE TITLE
[REQUEST] Add support for a portable installation in the installer

### ISSUE THREAD

**Issue by bashenk** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#145]
**Is your feature request related to a problem? Please describe.**
I got tired of manually selecting (or having to copy/paste) the portable app base and profile directories.

**Describe the solution you'd like**
It would be useful if I could simply run the exe normally and it would search perhaps a few common portable app locations.
For example, `C:\PortableApps\FirefoxPortable`. Perhaps search on additional drives. Other suggestions welcome.
If computation time / performance is an issue, perhaps only search for a portable instance as a last resort if a main installation cannot be found.

**Describe alternatives you've considered**
For my personal use, I ended up making a script to run the exe with the necessary values I need hardcoded.

**Additional context**
I started working on this sort of thing myself, but I am a relative novice at python, and the [Quantum-Nox-Installer.py](../tree/master/Installers/Multirow%20&%20other%20functions/Quantum-Nox-Installer.py) file is a lot to unpack. Additionally, I don't have a lot of time to devote to this anyway.
I can understand if this isn't a priority, but if the implementation isn't that challenging for you then I figured I might as well ask.

**Comment by bashenk** [comment]
> Yes, that's what I meant when I said:

I must've been tired when I first read your response, my bad. 

Just tried it out. That works fine enough for me. Thanks a lot!
I also noticed Windows didn't yell at me for the file download this time, which was a nice surprise as well 😄 

We could close this now, unless you still have something to work out for version 2 of the installer, as you mentioned once previously.

**Comment by Izheil** [comment]
>I also noticed Windows didn't yell at me for the file download this time, which was a nice surprise as well 😄

I'm sure they'll get paranoid soon enough with the file again, it happens randomly for them for any python-generated executable, but gladly not today!

>We could close this now, unless you still have something to work out for version 2 of the installer, as you mentioned once previously.

I'll close this then, version 2 will have the autoupdate feature, so it won't require to install it more than once, still, I'll try to implement this feature there as well.
