### ISSUE TITLE
[BUG] uBlockOrigin's click2load icon

### ISSUE THREAD

**Issue by Elaborendum** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#147]
**Describe the bug**
When using uBO's click2load, the icon meant to open the iframe in a new tab remains dark.

**To Reproduce**

1. Go to moz-extension://UUID-OF-UBLOCK-ORIGIN/web_accessible_resources/click2load.html
2. See icon

**Expected behavior**
Icon is a light color with enough contrast with the background.

**Screenshots**
![image](https://user-images.githubusercontent.com/71190696/143730238-7fbc7f87-0a19-49ad-b358-39154eb43783.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version FF94.0.2

**Comment by Izheil** [comment]
Should be fixed now on the [lastest commit](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/commit/1dc4583ad4c8c4e46358ea7b46777fa553caf584).

**Comment by Elaborendum** [comment]
Thank you
