### ISSUE TITLE
FF96 theme handling

### ISSUE THREAD

**Issue by AuRiMaS666** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#150]
FF96 has changed something in the way it handles themes and the default Dark theme is displayed like this with no third party personas applied.

![2022-01-14_11-49-47](https://user-images.githubusercontent.com/59185222/149498012-ea58f6d2-4bb0-4513-aec0-d7a691c27c81.png)

To compare, older versions looked like this, which I would prefer.

![144759669-1ee5a466-fc2d-40bf-9484-d3a5099f089d](https://user-images.githubusercontent.com/59185222/149498236-81650cbd-8540-4355-8d09-1590fdec491b.png)

**Comment by Izheil** [comment]
Should be fixed for both the rounded tab borders and default dark theme on userChrome.css file and rounded-connected-tabs.as.css files with the [lastest commit](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/commit/b61e57bd76ba9831c37d9e3f1c4377a379d760ef).

**Comment by AuRiMaS666** [comment]
All good now.

Thank you.
