### ISSUE TITLE
Theme does not cover the whole window/tab area

### ISSUE THREAD

**Issue by tungmilan** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#25]
Hello,

I'm not sure if this error is related to your theme or not but you might be the right one to ask

I'm using this theme on Firefox 63.0 / Windows 10 Home 64-bit
https://addons.mozilla.org/en-US/firefox/addon/dream-of-waves/

but it leaves a white margin to the left of the FF window on my external monitor (24" Dell ST2410) (nothing wrong on my 15.6" laptop screen btw)

![ff_err](https://user-images.githubusercontent.com/6590141/47613317-4f706080-da4a-11e8-9886-9f0f1e674335.PNG)

What could be the cause for this? Thanks!

I have all these files in my `chrome` folder 
https://github.com/Izheil/Firefox-57-full-dark-theme-with-scrollbars/tree/master/Scrollbars%20%26%20tooltips%20dark%20theme/Chrome

`userChrome.css` :

```

/* DO NOT DELETE THIS LINE */
@namespace url("http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul");

/* This enables the use of JS external files */
toolbarbutton#alltabs-button {
	-moz-binding: url("userChrome.xml#js")}
```

**Comment by Izheil** [comment]
Hmm.... none of the files in there except maybe multirow should affect the toolbox (and even then, multirow only affects the tabs element, not the #main-window element, which is where all the things are).
Does it happen with other lightweight themes?

Either way, we can do a simple fix for this. Add these to <code>userchrome.css</code>:

<pre>
/* Fix for some lightweight themes not working properly */
:root:-moz-lwtheme[lwtheme-image] {
  background-position: left top !important;
  background-size: contain !important;
}
</pre>

That should make the image stretch to the full size of the container it's in. If for some reason it shows it like that after trying the code, then that would mean that somehow it's recognizing the container as being moved to the right, in which case we could always just add some negative margin to the image, although... that shouldn't be necesary.

**Comment by tungmilan** [comment]
Thank you @Izheil ! That fixed it!

**Comment by tungmilan** [comment]
Even though it's not perfect but I can live with it for now

![ff](https://user-images.githubusercontent.com/6590141/47621360-ce4db380-dab3-11e8-8d1e-1688b1f8d3c7.PNG)

**Comment by Izheil** [comment]
It seems that the active tabs register the background as if it was still aligned to the right (kind of odd that they would make the tab inherit the background instead of just leaving it transparent, but only mozilla knows why they made it like that).
The corrected code should be this instead:

<pre>
:root:-moz-lwtheme[lwtheme-image], #tabbrowser-tabs:not([movingtab]) > .tabbrowser-tab > 
.tab-stack > .tab-background[selected="true"]:-moz-lwtheme {
  background-position: left top !important;
}
</pre>

There shouldn't be a need for <code>background-size: contain</code>, and should look better without it (as it should look by default), so try that, and if it doesn't align right, insert the contain rule again.

**Comment by tungmilan** [comment]
Thanks @Izheil ! Unfortunately that fix moved the problem from the left to the right of the Firefox window

![](https://i.imgur.com/6zexT74.png)

**Comment by tungmilan** [comment]
Looks like the final fix should be

```
:root:-moz-lwtheme[lwtheme-image], #tabbrowser-tabs:not([movingtab]) > .tabbrowser-tab > 
.tab-stack > .tab-background[selected="true"]:-moz-lwtheme {
  background-position: left top !important;
  background-size: contain !important;
}
```

**Comment by tungmilan** [comment]
The latest update of Firefox (66.0) broke this again I think. Now my bookmark bar is white

![](https://i.imgur.com/obI1ngK.png)

**Comment by Izheil** [comment]
Hmm.... I just installed it and it seems alright, are you using the lastest version of that extension theme (if you had it for a long while it won't be autoupdated, so you may have to reinstall it)?

**Comment by tungmilan** [comment]
Yes I'm using the latest version (today). The scrollable version from this folder
https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/tree/master/Installers/Inst_files/chrome

This is my `userchrome.css`

````
/* DO NOT DELETE THIS LINE */
@namespace url("http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul");

/* This enables the use of JS external files */
toolbarbutton#alltabs-button {
    -moz-binding: url("userChrome.xml#js")}
	
/* Fix for some lightweight themes not working properly 
https://github.com/Izheil/Firefox-57-full-dark-theme-with-scrollbars/issues/25#issuecomment-433745009 
*/
:root:-moz-lwtheme[lwtheme-image], #tabbrowser-tabs:not([movingtab]) > .tabbrowser-tab > 
.tab-stack > .tab-background[selected="true"]:-moz-lwtheme {
  background-position: left top !important;
  background-size: contain !important;
}

````

**Comment by Izheil** [comment]
Hmm.... Everything seems in order.
Try <code>background-size: cover</code> instead of contain, and if that doesn't solve it check if it still happens without multirow enabled.

**Comment by tungmilan** [comment]
Thanks @Izheil ! Changing to `cover` fixed it but then the light theme was gone too

![](https://i.imgur.com/nnDkInb.png)

**Comment by Izheil** [comment]
I'm not sure how userchrome or multirow could be affecting the persona...
If you have already tried disabling them both and the problem persists,  it sounds like some setting on your Firefox might have gone corrupt.

Try entering [Firefox safe mode](https://support.mozilla.org/en-US/kb/troubleshoot-firefox-issues-using-safe-mode) (not refreshing it) and see if it still happens.

**Comment by tungmilan** [comment]
@Izheil This happened to a freshly installed Firefox on a new computer too. But I can live with it for now

**Comment by Izheil** [comment]
If it's not related to multirow or any of the files here, I don't think I can help then.

**Comment by tungmilan** [comment]
@Izheil : there must be something with the theme. I tried both your suggestions as well as deleted all those lines specific for that theme. Nothing worked

**Comment by Izheil** [comment]
Well, I guess we can try one last thing.

Download the header image of the theme you are using:
![Dream-Waves](https://user-images.githubusercontent.com/33794458/54875732-80d83700-4e04-11e9-9cc6-16cf6bc46712.png)

Place it somewhere where you can keep it (the chrome folder will do), and link it as the header image like:

<pre>
:root:-moz-lwtheme {
  --lwt-header-image: url("file:///the-path-of-your-file.png") !important}
</pre>

To know the path of your file, you can just drag the image once you download it and place it somewhere into firefox, and the path will appear inside the URL box.

That should replace whichever header you currently have with the image you specify. Then you only have to swap to any persona you want that also has a header image, and it will be replaced.
