### ISSUE TITLE
Change color visited link on firefox ?

### ISSUE THREAD

**Issue by NicotherZ** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#30]
How change color visited link on firefox ? Not website link, firefox link like SS :

![how change](https://user-images.githubusercontent.com/12177860/50055301-7e06df80-014d-11e9-876f-53ed523fe998.jpg)

Thanks in advance for your help!

**Comment by Izheil** [comment]
You can change the color of the links inside <code>usercontent.css</code>, on line 86, under the "FILE BROWSING PAGE" section. All link related lines are the ones with an a rule:

<pre>
#UI_goUp a.up:link, a.file:link, a.dir:link {color: #09f !important}
#UI_goUp a.up:visited, .ellipsis a.file:visited, .ellipsis a.dir:visited {color: #0070aa !important}
#UI_goUp a.up:hover, .ellipsis a.file:hover, .ellipsis a.dir:hover {color: #0ff !important}
#UI_goUp a.up:active, .ellipsis a.file:active, .ellipsis a.dir:active {color: #0050dd !important}
</pre>

You'd want to change the "visited" line color (should be on line 86, aka the <code>#UI_goUp a.up:visited, .ellipsis a.file:visited, .ellipsis a.dir:visited {color: #0070aa !important}</code> specifically.

Some alternative common color for visited links is purple, so <code>#7070aa</code> would do the trick, but if you aren't fully convinced with that, you can choose any other color checking it's hex value <a href="https://www.w3schools.com/colors/colors_picker.asp">here</a>.

**Comment by NicotherZ** [comment]
I could put the color I wanted ,thank you!
