### ISSUE TITLE
Scrollable tabbar changes scroll when clicking on a tab other than first visible row

### ISSUE THREAD

**Issue by PaddlesAU** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#36]
I've found an issue where if I have enough tabs to have a scrollable tab bar, and I click on a tab that is not in the first visible row, the tab bar rescrolls so that the row containing the tab I just clicked on is scrolled to the top of the tab bar. This is annoying because I didn't want the tab bar to rescroll.

For example, suppose there are six rows of tabs, but the scrollable tab bar only shows 3 at a time, and currently rows 1-3 are visible. If I click on one of the tabs in row 2, then the tab bar scrolls so that rows 2-4 are visible.
In this case the desired behaviour would still be to activate the tab in row 2, but for the tab bar to show rows 1-3 not 2-4. 

(Obvious exception: if the tab clicked is one of the final rows, the tab bar scrolls as far down as it can. So continuing the above example, clicking on a tab in row 5 would mean that rows 4-6 are visible in the tab bar.)

Observed on FF65.0 64-bit on Win 10 1803 with all extensions disabled; using Izheil Theme features and multi-row, not theme colours. Altered CSS settings:
* --max-tab-rows set to 4
* .tabbrowser-tab min-width and max-width set to 100px

**Comment by Izheil** [comment]
I just updated it now so that it only scrolls how it's suposed to. Sorry for the inconveniences.

Looks like the issue was that it always scrolled to the selected tab without checking if it was already visible or not. Now it only scrolls to it when not visible (which should solve the issue).

**Comment by Izheil** [comment]
I found a better way to fix scrollability of the tabs, so now it should scroll to the nearest edge of the container when selecting a non-fully-visible tab. 

I also added a smooth transition for the scrolling, so it should feel more in line with how default Firefox used to beheave.

As for the donations... I don't think that many people would want to donate, so I never gave much though on it.

**Comment by PaddlesAU** [comment]
Tested, all looking good. Thanks!
