### ISSUE TITLE
Opening bookmark in a new tab

### ISSUE THREAD

**Issue by Lim4multirowtab** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#42]
Hi Izheil,

I don't know if it is directly related to your coding and development, but since I use it, when I click on a bookmark (from the sidebar), it opens in the current tab and not anymore in a new tab.

Is this something that I can change in some line(s)to revert back to the previous behavior?

Thanks,
Lim.

_PS: I have added a last comment in the closed "Current tab offset up" issue._

**Comment by Izheil** [comment]
That's not something related to the files from this repository. The only things this repository change are the looks of firefox, and adding multi-row tabs/bookmarks.

You can change that behaviour in <code>about:config</code>, changing the parameter <code>browser.tabs.loadBookmarksInTabs</code> to true (just left click it twice).

**Comment by Lim4multirowtab** [comment]
Strange. It was already modified to True.
Then I changed to False (Default) and now it works back as expected : bookmark opens in a new tab instead of the current one.

Once again, thank you for your knowledge and help !
