### ISSUE TITLE
New tab button doesn't work after update on FF 66

### ISSUE THREAD

**Issue by Andrey-Shulga** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#47]
Today I updated on FF66, and new tab button doesn't work, no reaction when I press it. If I delete MultiRowTabLiteforFxFF66.uc.js all work well.

**Comment by Izheil** [comment]
I can't seem to replicate the issue on W10 with neither FF66 nor FF68 (with neither scrollbar nor the lite version).

Make sure that you are using the lastest <code>MultiRowTabLiteforFx.uc.js</code> from the repository and that you don't have any custom code that might affect the tab toolbar on <code>Userchrome.css</code>.
