### ISSUE TITLE
Change unread tab color

### ISSUE THREAD

**Issue by gioruggieri** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#52]
How change unread tab color?

**Comment by Izheil** [comment]
In your userChrome.css, copy the <code>/* TAB READ/UNREAD COLORS */</code> section of <a href="https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/blob/master/CSS%20tweaks/Tab-related-Tweaks.css">Tab-related-Tweaks.css</a> (line 69 to the end), and then change the "color" values to the ones you want for each tab state.

For the unread (but loaded) tabs, you also need to enable the [unread] state on tabs (Firefox removed that state in certain version, so you need to patch Firefox to customize that now).

The setAttribute_unread.uc.js file adds the [unread] state to the tabs, but to use it you need to patch Firefox to be able to use JS files.

You can do this by using <a href="https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/releases/tag/FF73">the patcher</a> (If you are using windows or linux), selecting your Firefox version in the left, and the "Enable unread state on tabs" option on the right section.

Alternatively you can patch it manually following the guide in <a href="https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/tree/master/Multirow%20and%20other%20functions/JS%20Loader">JS Loader</a> section in the repo and then copying the <a href="https://raw.githubusercontent.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/master/CSS%20tweaks/Tab-related-Tweaks.css">setAttribute_unread.uc.js</a> file inside your Chrome folder (I don't recommend doing this manually unless something goes wrong with the installer or unless you use MacOS).

Once that's done, your chrome folder should have "utils" folder, "userChrome.css" and "setAttribute_unread.uc.js" files in it at least.

When your Firefox is patched, just change the "color" value in userChrome to whatever you want for text.

For example, if we want to use gray italiced text on unread tabs:
<pre>
.tabbrowser-tab:not([selected="true"])[unread] .tab-label {
  color: #eee !important;
  font-style: italic !important;
  font-weight: normal !important}
</pre>
