### ISSUE TITLE
Tabs Below Causes Icons Placed on Main Menu to Wrap

### ISSUE THREAD

**Issue by Ryushin** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#55]
![Firefox_Main_Menu_Icons_Row](https://user-images.githubusercontent.com/4388558/76705010-6ac12780-66a2-11ea-9676-02b092d08fe8.png)
![Firefox_Tabs_on_Bottom_Icons_Wrap](https://user-images.githubusercontent.com/4388558/76705011-6b59be00-66a2-11ea-893f-da929d99180c.png)

**Describe the bug**
Using Tabs Below on Firefox 74 and Nightly to and placing any add-on icons in the Menu Bar causes them to wrap down the left side one icon at a time.

**Expected behavior**
Icons should display in a row.

**Desktop (please complete the following information):**
 - OS: Linux
 - Version FF74, Nightly

I've attached an image with tabs below showing the icons are wrapped from the Main Menu and another that does not have tabs below enabled and it shows the icons in a row on the Main Menu.  Tabs Below worked properly with displaying a row of icons on the Main Menu with FF73 and below.

**Comment by Izheil** [comment]
Thanks for reporting it with good detail! 
The issue should be fixed now, along with other minor issues tab below had as of lately.

**Comment by Ryushin** [comment]
Works wonderfully now.  The minor issues fixes were also welcomed as I did not have to tweak the new file at all.  Thank you for all your work with Multirow tabs and tabs below.  Your tool is the only reason I've been able to move to the modern version of Firefox from  the pre-quantum Firefox and Waterfox.
