### ISSUE TITLE
Last exe path for windows doesn't put MultiRowTab-scrollable.uc.js

### ISSUE THREAD

**Issue by Zipfer** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#58]
**Describe the bug**
MultiRowTab-scrollable.uc.js not inside chrome folder after patching

**To Reproduce**
Steps to reproduce the behavior, or a brief explanation on it:
1. Run patch select two folders 
2. Close FF75
3. Open multiple tabs
4. No tab rows 

**Expected behavior**
After patching multirow working by default.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows
 - Version FF75

**Comment by Izheil** [comment]
I just tested the patcher and it's copying MultiRowTab-scrollable.uc.js fine on both my profiles when selecting both with either the default paths or with the profiles only list.

You need to patch your firefox installation before using any of those functions first, so you need to tick "Firefox" and patch at least once.

Once your Firefox is patched you can use the "Profiles only" section without the need to repatch Firefox in upcoming updates to install the functions in more than one profile at a time.

To check if MultiRowTab-Scrollable.uc.js is installed at least in your default firefox profile, you can click the "Open profile" button in the patch status section.

If the file is not there after patching, are the profile folder paths of both of the profiles you are trying to patch shown in the correct folders in the installer?

**Comment by Izheil** [comment]
Any news on this?
