### ISSUE TITLE
[BUG] PLUS/new tab button hidden when moved to left side

### ISSUE THREAD

**Issue by TimurBorn** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#66]
**Describe the bug**
The PLUS/new tab button to open a new tab is hidden when it is moved to the left/front of the tabs.

**To Reproduce**
Steps to reproduce the behavior, or a brief explanation on it:
1. Start Customize.
2. Move PLUS/new tab button to upper left.
3. Leave Customize.
4. Button vanishes.

**Expected behavior**
The PLUS/new tab button should stay visible to the left of the tab row.

**Desktop (please complete the following information):**
 - Windows 10 1909
 - FF 76.0.1

**Comment by Izheil** [comment]
Should be fixed now.
Fetch the lastest [Multirow](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/tree/master/Multirow%20and%20other%20functions/Multirow%20tabs) or re-install through the new [patcher](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/releases).

**Comment by TimurBorn** [comment]
Yes, it is fixed now. Thanks for the quick response!
