### ISSUE TITLE
[BUG] Windows refuses to execute, defender detects it as Trojan

### ISSUE THREAD

**Issue by einicher** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#78]
Downloaded Multirow-Patcher-Quantum-Nox-Installer-Windows-1.7.5.exe, got a defender notification that it detected a threat. When i doubleclick on the exe a blue window pops up telling me this could harm the system leaving me only one option: "do not execute".

I am a linux user - there the patch worked fine - dont know how to deal with this on windoofus. How can i force it to execute? Run as administrator does not work either.

![grafik](https://user-images.githubusercontent.com/948188/91284635-773ac780-e78c-11ea-966b-855c63f17724.png)

**Comment by Izheil** [comment]
Yes, AVs don't seem to like any binary made with pyinstaller... You can see more details about that on [issue #54](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/issues/54).

There are a few ways to unblock it (The first one might not appear for you, if that's the case use the second):
1. Select properties of the installer, and tick the "unblock" checkbox of the security section of the "general" tab (if that appears for you, which... should when you have smart screen enabled), which should unblock this one file only.
![unblock a file from properties](https://geeksadvice.com/wp-content/uploads/2019/10/unblock-file-windows-defender-smartscreen-1024x576.jpg)

2. Go to windows settings > Update and security > Windows security > App & Browser control > Disable "Check apps and files", or leave it as "warn" if they give you that option. This will disable smartscreen, which is the one that prevents you running it. You can re-enable it later after running the file if you want.
![imagen](https://user-images.githubusercontent.com/33794458/91293366-30eb6580-e798-11ea-99a3-ca5a15c1783f.png)

![imagen](https://user-images.githubusercontent.com/33794458/91293431-4a8cad00-e798-11ea-8dfc-399c97c6650e.png)

![imagen](https://user-images.githubusercontent.com/33794458/91293301-16b18780-e798-11ea-9023-4a95c21ce775.png)

**Comment by einicher** [comment]
Thank you for the quick answer.

I did both, check the unblock in properties and disable "Check apps and files". Result is another alert telling "this app cannot be executed on this pc, contact your software maintainer to get a compatible version of this executable".

Now it gets funny: i deleted an redownlaoded the file, in case defender corrupted it somehow. But as soon as i executed the file it disappeared and notification popped that threats were found an dealt with.  But "check apps and files" is disabled.

![grafik](https://user-images.githubusercontent.com/948188/91385841-0f3ebc80-e832-11ea-9086-437aa1407fd0.png)

![grafik](https://user-images.githubusercontent.com/948188/91386428-46fa3400-e833-11ea-9870-f90b7e537927.png)

**Comment by Izheil** [comment]
Ah right, we only disabled smartscreen, but Windows Defender is still running.
After disabling smartscreen you'll have to go to "protection against virus and menaces" (Viren- & Bedrohungsschutz) and temporally disable real-time protection (I'm not sure if the others are necessary to be turned off). 
![Temporally disabling WD](https://fossbytes.com/wp-content/uploads/2018/11/Disable-Windows-Defender.jpg)

After disabling both smartscreen and WD, it should let you run it. 
Make sure to re-enable WD later (although suposedly windows should re-enable it in the next login if you turned it off).

**Comment by einicher** [comment]
Yes! that worked.
Thank you!
Tabs get really tiny though, down to 75px or so.

**Comment by Izheil** [comment]
That should not happen as far as you aren't using any tab-related code on `userChrome.css`, didn't set `--tab-growth:` variable inside the multirow tabs file to 0, or changed `browser.tabs.tabMinWidth` on `about:config`.
