### ISSUE TITLE
[BUG] Hover Window Above Bookmark Entry is All White

### ISSUE THREAD

**Issue by monkeylove** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#79]
**Describe the bug**

When I display the bookmark using the "show sidebars" button and hover the mouse cursor on top of a bookmark, the window is all white.

**To Reproduce**
Steps to reproduce the behavior, or a brief explanation on it:
1. Click "show sidebars" to open the sidebar, and go to bookmarks.
2. Move the mouse cursor and hover on a bookmark.
3. A white window hovers over it.

**Expected behavior**
There's supposed to be text in the window.

**Screenshots**

![whitewindow](https://user-images.githubusercontent.com/5005509/91637674-b2632200-ea3c-11ea-9eb7-baf3d7757eaf.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home SL x64
 - Firefox 80 64x

**Additional information**
I used the files in the repository follow the installation instructions. When I disabled the CSS to check, the window with text showed up correctly.

**Comment by Izheil** [comment]
That gets changed by the `tooltips.as.css` file, but since it's optional, I added some fix for it now, so it should display correctly even when not using it after the last update.

Try the new version and see if that resolves the issue.

**Comment by monkeylove** [comment]
Yes, it's working fine now. Thank you!

**Comment by monkeylove** [comment]
Yes, it's working fine now. Thank you!

**Comment by monkeylove** [comment]
Yes, it's working fine now. Thank you!
