### ISSUE TITLE
Problem with uBlock element picker mode

### ISSUE THREAD

**Issue by tkhquang** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#8]
Whenever I enter this mode, seems that the overlay makes things hardly readable. Here is the screenshot:

I did some research and it seems that "@-moz-document url(about:blank)" in the userContent.css is the cause of this problem, but I'm not so sure, hope that you will take a look into this.

Thank you so much for the hard work!

**Comment by NicotherZ** [comment]
Same problem here, please help us :)

**Comment by Izheil** [comment]
Sorry for the late response! 
Aparently Github decided I shouldn't receive a notification about the issue until now.

Anyway, sorry for the inconvenience, I uploaded the fix to the userContent files. You can just redownload any of the userContent.css files from any of the folders, or if you want, you can edit the fix yourselves if you are using a modified version of userContent. 

The problem seemed to be that Ublock element picker uses the about:blank page as an overlay as @tkhquang pointed. 

So on line 392 you'd have the "url(about:blank)" selector which then would be given a dark background with superior relevance to override the default color of blank pages (they would appear when some page takes long to load), which also seems to override the transparent color that ublock gives to the element picker overlay.

To fix this, just delete the "url(about:blank)" from line 392, and add this rule on line 399:

<pre>
/* Fix for Ublock Origin Element picker */
@-moz-document url(about:blank) {
	body {background: #222}
}
</pre>

Without giving it an "!important" relevance, we can still override the default background color of <code>about:blank</code>, and also get overriden by any other CSS rule that may need to make it transparent using an "!important" attribute (which is how it's done in Ublock).

**Comment by NicotherZ** [comment]
Works great ! Thanks ;) Personnaly i have just wait 5 hours for your reponse, so, very fast !! ;)

**Comment by tkhquang** [comment]
Thanks, eveything is fine now 😄

**Comment by rbr** [comment]
For any people searching in their customized files; here's the commit that fixes this issue; https://github.com/Izheil/Firefox-57-full-dark-theme-with-scrollbars/commit/54c341a5af058379236025231258892ef00b8e70.
So you have some context to look for, since line numbers will vary.

**Comment by jingofett** [comment]
Having an issue with element picker mode. I don't know if this is the same issue as the screenshot seems to have expired but this is what I'm getting:

![a4810ba9-2cf6-492e-baae-0c6a9d689578](https://user-images.githubusercontent.com/8313249/94762680-edd47180-0397-11eb-9fb8-e788e545299e.png)

**Comment by Izheil** [comment]
Should be fixed with [a4ecaee](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/commit/a4ecaee6ea566b5654f8d46b14442b5a406b5c9a). 

Modify the lines from the commit on your addons.css file, or update it using the [UUID replacer](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/releases/tag/1.0.0) while selecting the right profile.

**Comment by jingofett** [comment]
That worked, thanks!
