### ISSUE TITLE
[REQUEST] Tab borders, Close tab button, Unread Tabs Grayed out - can they be editable features?

### ISSUE THREAD

**Issue by dlc2001** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#82]
Hello, 

I have been using your MultiRowTab for some time now and I really like it.  I notice that you have a part where you say "here are the  editable variables" and "don't edit past here unless you know what you are doing".  I've been living dangerously because, um, I really don't know what I'm doing and I have been "editing past here" for two features that I like and found code for somewhere else.  It'd be great to see you add them to the editable section - make them "legal" so to speak.  If you could also fix the bug in my code that'd be great ;-)

I'm doing two things:
1. I like to have the tab close button always visible.  I found this code and it works to have a tab close button on all non-pinned tabs.  

#TabsToolbar #tabbrowser-tabs .tabbrowser-tab:not([pinned]) .tab-close-button {
    visibility: visible !important;
    display: block !important}

#TabsToolbar #tabbrowser-tabs .tabbrowser-tab:not([pinned])[faviconized="true"] .tab-close-button {
    visibility: collapse !important;
    display: none !important}

2. I like to have borders around my tabs and I like the edges rounded.  Like the old firefox.  I found code that does that pretty close to the old firefox.

.tab-background {
	border-radius: 5px 5px 0px 0px !important;
	border-style: solid solid none !important;
	border-color: gray !important;
	border-image: none !important}

	.tab-line {
	margin-left: 12px;
	margin-right: 12px} 

Unfortunately there's a bug somewhere in this code, because when I implement it I get the things I want but also there's now an "offset" for tabs in my second row when I have two rows...  the second row starts just below the first unpinned tab instead of just below the first pinned tab.  Oops...  But this is the gist of it...

If these things are already implemented in some other way that I'm just ignorant of, my apologies... I fully admit that I am wandering around not knowing what I'm doing.  

A third feature (is it a bad idea to put three feature requests in a single request?  If so, apologies again) is that the old firefox has unread tabs "grayed out" and it'd be nice to have that too.  I see you have an "unread state" part of your theme so maybe I'm just not implementing it correctly, but if it's a feature you don't already have, it'd be nice to have.  But I have no code to suggest for it... 

Regards, DLC

**Comment by Izheil** [comment]
For tabs always visible, the code is already included in the [CSS Tweaks](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/tree/master/CSS%20tweaks/Tabs) folder, and you can just save it as a separate file to install on your chrome folder [here](https://raw.githubusercontent.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/master/CSS%20tweaks/Tabs/Tab-close-button-always-visible.as.css).

As for the second, it's not a problem with your code, but with the overflow status that Firefox added a few versions back... It should be fixed on the last version of multirow now.

The third already exists, the script only allows you to modify unread tabs tagging them as such, you can modify them using the [template](https://raw.githubusercontent.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/master/CSS%20tweaks/Tabs/Tab-state-coloring.as.css) on the [CSS tweaks/Tabs](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/tree/master/CSS%20tweaks/Tabs#tab-fixes) folder.

**Comment by dlc2001** [comment]
Ah, I see... thank you!  I was able to implement the first two using the CSS tweaks, thus leaving the multirow js in its "native" state.  The third thing, the unread tabs, I need to play around with a bit to understand the nuances of the states, and I'll need to decide what background colors I want, so that'll probably not happen for a few days.  But the original .css file from your tweaks folder is currently residing in the chrome folder while I wait to have time to tweak it.  So my chrome folder now has:  MultiRowTab-scrollable.uc.js, Rounded-tabs-basic.as.css (with my tweak as above), setAttribute_unread.uc.js, Tab-close-button-always-visible.as.css, userChrome.css (which is empty), and userChrome.xml.  

I am being specific above about my current setup because: I wasn't able to use the latest version of multirow tabs.  If I use it in its "native" state, it "does no harm" - that is, my first tab in the second row is below the first non-pinned tab in the second row, as before.  However if I change tab-growth to 0, the thing goes kind of nuts... basically every second, the second row is shifting from underneath-the-first-tab to underneath-the-first-non-pinned-tab.  This leads to a kind of "flickering" effect.  I am on Firefox 80.0.1.  I'm out of time for today so I can't test to see if it's an interaction with the css's but I thought I'd let you know...

Regards, dlc

**Comment by Izheil** [comment]
userChrome.xml?

You shouldn't have that file anymore... if you have userChrome.css with just the old userChrome.xml binding, you should remove it along with userChrome.xml

With the JS loader patching you shouldn't have any issue (You can even use the installer for that on the [releases page](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/releases/tag/FF80) if you didn't have it already).

The userChrome.xml binding might be interfering with the overflow hidding, and the "there is only xul" line also seems to cause some issues, so despite some users saying that it should be used... there is no reason to use it at all anymore.

I'm testing with 1-4 pinned tabs and multirow seems to be working fine here with your same setup, so it must be the .xml binding.

I only tested on Windows 10 (should work on Linux and Mac), so that's another possible reason... what OS are you using?

**Comment by dlc2001** [comment]
OK, removed userChrome.xml.  Yes Windows 10 Pro.  Yes I used the JS loader patching.  Multirow-Patcher-Quantum-Nox-Installer-Windows-1.7.6.exe , did it again after I removed the userChrome.xml just to be certain.  userChrome.css is your empty shell.  Tabs in second row still start below first non-pinned tab.  I commented out my tiny hack to the tab borders and no effect.  Strange.  Could vestiges of the .xml still remain, do I need to clean out a cache or something?

**Comment by dlc2001** [comment]
Additional info: if I remove all .css' from the folder it works with tab-growth = 1; so it's an interaction.  Stay tuned.

**Comment by dlc2001** [comment]
Works with tab-growth =0. and no css'.  Works with tab-growth=0 and css' for rounded tabs (including my tweak) and with tab state coloring.  

Interaction is with tab close button css.  If I add that css, unhappiness in Firefox-land... flickering back and forth with tab-growth = 0, didn't check with tab-growth =1, assuming it'll be the same result as before.  

Pulled from here: https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/blob/master/CSS%20tweaks/Tabs/Tab-close-button-always-visible.as.css

'Couldn't attach actual file, "we don't support that file type".  But I copy/pasted the contents at that address (12 lines) into Notepad++ and saved with the name as noted.  This worked for the other two css'.  Dunno why it isn't working for this one.  Any other suggestions?

**Comment by dlc2001** [comment]
Sorry, I'm leaving a long trail of add-on messages because each time I keep promising myself I'll stop doing this and move on to what I'm actually supposed to be doing now.  I found the problem, but I'd be interested in a solution if you have a suggestion.  The problem is indeed the tab width.  In about:config, I had  browser.tabs.tabMinWidth set to 55.  If I reset it back to the default of 76, the problem goes away.   But MinWidth of 55 + a close tabs button is what I would prefer.

**Comment by Izheil** [comment]
It's fine, don't worry.

I uploaded a [new version of Multirow tabs](https://raw.githubusercontent.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/master/Multirow%20and%20other%20functions/Multirow%20tabs/MultiRowTab-scrollable.uc.js).

It simulates non overflow state when it's added instead of removing the overflow state (should work better).

**Comment by Izheil** [comment]
On a sidenote... the scrollbar will stop working with the wheel if setting the min width to anything lower than 58 (anything lower than that will make the tabs overlap each other and will set the focus on the invisible horizontal scrollbar, making the vertical one usable only when dragging it).

**Comment by dlc2001** [comment]
Success!!!  I did width = 60 per your sidenote.  All is well now, thank you!

**Comment by Izheil** [comment]
Glad you got it working!
I'll upload the installer for the new version and then close the issue.

**Comment by dlc2001** [comment]
Kk

**Comment by dlc2001** [comment]
Note. I didn't actually check to see whether it was the move to 60, or the new .js that did the trick... I made multiple changes at once.  I started from a base of width =76, which worked with the old .js, and moved to the new .js, then went down to 60.  :-)  Just for the record!!

**Comment by dlc2001** [comment]
Hi, I don't know if this will get to you now that the issue is closed.  I also don't know what's the best way to ask this question (email?  Open an issue thread?  Something else?).  But I started to play around with the tab-state-coloring.  I can get it to work no problem - this basically involved changing the background-color under the "not loaded yet (also visited) section.  But it had an interesting interaction with the rounded tabs css.  The tabs are still rounded, but that little corner that is "snipped off" by the rounding is not the right color.  It should be the color of the background of the tab area as a whole. 
I don't know if the words above make sense.  Here is a snip that might help.  The first arrow is pointing at the gap between tabs when the tabs are the default color.  The gap is the same color as the tabs, yes, but it is also the same color as the rest of the tab bar.  But if you look at the gap created by rounding the corner of the tab with the changed color, the rounding creates a rounded border but doesn't seem to actually indicate to the system that that border is the margin of the tab and therefore the tab color should end at the rounded corner, not at the pre-rounded border.  
Do you know why this would happen/how to fix?  Thank you.  




    On Sunday, September 6, 2020, 07:17:33 PM PDT, Izheil <notifications@github.com> wrote:  
 
 


Closed #82.

**Comment by Izheil** [comment]
On your rounded tabs file change the `.tab-background` selector for `.tab-content` and it should fix the issue.
You might need to also increase your border-radius to keep tabs looking rounded after that.

**Comment by dlc2001** [comment]
Got it, thank you!!
    On Wednesday, September 9, 2020, 06:21:06 AM PDT, Izheil <notifications@github.com> wrote:  
 
 


On your rounded tabs file change the .tab-background selector for .tab-content and it should fix the issue.
You might need to also increase your border-radius to keep tabs looking rounded after that.

**Comment by dlc2001** [comment]
Hi, 
Back last year you helped me with some rounded-tabs stuff and tab-state-coloring stuff, which I very much appreciated.  All worked great until this latest update.  I downloaded the latest patch/update and it was supposed to deal with padding.  I'm not sure it did.  I'm hoping you might have a simple suggesttion for my new issues.  I have two problems/questions:
1. First, regarding the spacing between tabs: is this what you mean by "padding"?  
Here is "before" (from a browser I haven't updated yet).  Tabs basically abut each other.  



After, I tried it with and without the rounded-tabs-basic.as.css that I was using in the above photo... since that .css is no longer listed in your Tabs section.  But the tabs are just not as close as they were before.  
This is with the rounded tabs css: the leftmost tab is a pinned tab and the others are not:



This is without the rounded-tabs css; again, the leftmost tab is a pinned tab and the others are not.  There's still space between the tabs which there really wasn't in the "before".  




Is it something I did with my other .css's?  Is this the "padding" you were trying to fix or is this something else?  

2. The second thing is the color.  In the first image, you see there's a lot of dark gray, including the tabs themselves.  Now, "awake" tabs are light gray.  I understand that that's because I have "transparent" for background color of awake tabs in my tab-state-coloring.as.css.  But... I didn't intentionally change anything from dark gray to light gray, and the background against which the tab used to be transparently dark gray, is now light gray, as is my menu bar. 

(I know why the tabs are wider - I intentionally didn't change that - it's the background color I'm finding interesting).  I don't know how/why that happened with the Mozilla update but... how do I change that, what's the variable name for that and can I change it in the tab-state-coloring.as.css?     
NOTE: my tab width is 58 and I did the compact density to reduce the tab height to approx what it was in the "before" image.  
Thank you for any suggestions you might have, I very much appreciate your offering these add-ons!!
-----
On Friday, September 11, 2020, 05:51:57 PM PDT, dlchu ***@***.***> wrote:  
 
  Got it, thank you!!
    On Wednesday, September 9, 2020, 06:21:06 AM PDT, Izheil ***@***.***> wrote:  
 
 


On your rounded tabs file change the .tab-background selector for .tab-content and it should fix the issue.
You might need to also increase your border-radius to keep tabs looking rounded after that.

**Comment by Izheil** [comment]
I can't see any of the screenshots you posted, but Proton (the lastest UI update) changed how tabs are displayed dramatically.

I removed the rounded tab scripts since now tabs are rounded by default. Sadly they also come with added "margins" between tabs.

By padding I mean all the empty space they added inside and around tabs (at least now). They added empty space around tabs, which is part of Proton, so a new CSS would be required to change it to look rounded, without spaces, and connected to the toolbar as it was before.

As for the color... yes, that's another "feature" of Proton, in dark mode now tabs are lighter colored than the rest of the toolbar.

I also removed the coloring of tabs after proton due to some issues with it with hovered tabs, since I didn't think anyone changed the color of anything apart from the selected tab, but I could add it back and see if I can work around it.

As for the rounded tabs, would you mean them to be connected to the toolbar while being rounded on top as it was back with `rounded-tabs-basic.as.css `, while removing all empty spaces between tabs?

**Comment by dlc2001** [comment]
For the record, try 2 on the images.

Pre-Proton, your multi-row, not dark theme.  Tabs close together, active tab lighter than background (I wrote that incorrectly in my previous post, sorry - don't know how I achieved that with background set to transparent), and area around tab and behind menu, kind of a dark gray.

![Pre-Proton](https://user-images.githubusercontent.com/70833643/120865121-428d4500-c542-11eb-9421-3145a1ad1aef.jpg)

Post-Proton, your multi-row, not dark theme, colors css,, no rounded tabs css.  Tabs farther apart, background color much lighter.  No active tab in this image, sorry.  

![Post-Proton, No rounded-tabs-css](https://user-images.githubusercontent.com/70833643/120865128-46b96280-c542-11eb-8d26-77ab6e01bc61.jpg)

Post-Proton, your multi-row, not dark theme, colors css, rounded tabs css.  No apparent ill effects to using rounded tabs css (does seem to lead to larger padding between pinned tab and non-pinned tabs, but otherwise appears benign).  I have the leftmost tab active in this screenshot, I assume this is what you are talking about when you say "disconnected from the toolbar"?

![Post-Proton, rounded-tabs-css](https://user-images.githubusercontent.com/70833643/120866351-96992900-c544-11eb-9f4b-337c7e3b87e2.jpg)

> I removed the rounded tab scripts since now tabs are rounded by default. Sadly they also come with added "margins" between tabs.

I tried it with and without the script and I liked it better with the script.  It doesn't seem to be breaking anything.  Here was my script:

.tab-content {
  border-radius: 10px 10px 0px 0px !important;
  border-color: rgb(211,211,211) !important;
  border-style: solid solid none solid !important;
  border-width: 3px 1px 1px !important;
  border-image: none !important}

>By padding I mean all the empty space they added inside and around tabs (at least now). They added empty space around tabs, which is part of Proton, so a new CSS would be required to change it to look rounded, without spaces, and connected to the toolbar as it was before.

Using the script above and your latest patch, the padding/empty space around the tabs is still there.  I just wanted to get clarification on what your intent was with the latest update.  When you said something to the extent that it was there to deal with Proton's padding, I thought you meant "give me the option to get rid of" but perhaps you just meant "make sure the script doesn't break because of the padding".  LOL.  It is what it is.

I guess I had my tabs more rounded than Proton's default, and I did have a slight border/margin but not as big as they had.  

Your rounded-tabs script also had margin-left and margin-right but when I played with those variables last Sept they didn't seem to be having any effect so I just left those alone.  

> As for the color... yes, that's another "feature" of Proton, in dark mode now tabs are lighter colored than the rest of the toolbar.

FYI, the rgb color in the script above was intended to somewhat match the background behind/between the tabs.  In the light mode (which I use, I just use your multi-row, not the full dark theme) they now made that background much lighter as you can see.  So I guess they did a similar thing with the dark mode.  I guess you are saying that I cannot change that background color with a css tweak in one of my existing scripts?  That was what I was trying to ask, regarding the color...  

>I also removed the coloring of tabs after proton due to some issues with it with hovered tabs, since I didn't think anyone changed the color of anything apart from the selected tab, but I could add it back and see if I can work around it.

I am also still using tab-state-coloring which also appears to be not-broken.  But I'm not sure why you say you removed coloring of tabs, since it is in your repository of CSS tweaks and says it was updated 2 days ago?  

>As for the rounded tabs, would you mean them to be connected to the toolbar while being rounded on top as it was back with rounded-tabs-basic.as.css , while removing all empty spaces between tabs?

See above explanation(s).  Sure, I would like to remove the empty spaces between the tabs!!  But - it is what it is, and whatever is possible, is possible and whatever isn't, isn't.  My questions were more an attempt to find out if I had broken something... apparently everything is working "as intended" at the moment?  If there's interest in fixing any of the above (get rid of padding, tweak my light gray back to dark gray, keep my tweaks to keep tabs more rounded without breaking anything) I'm happy to use the changes, but as long as I am not breaking anything I can keep on keeping on.   

Thank you.

**Comment by Izheil** [comment]
If you were using the simple rounded tabs I'm good with readding them and fixing them for proton, I'd just fetch the lastest version I had from the commits history and fix it to work on all possible themes (system, default light/dark, and lightweight themes).

As for the tab-state-coloring, I thought I had removed the background coloring since it had some conflict with the dark theme hover colors, but looks like I didn't in the end (I must have thought about some other changes I did, my bad). I still have to fix some things to make it work better with proton tho.

As for the padding INSIDE tabs, that's controlled by multi-row, using the `--tab-min-height` which I patched yesterday, which just changes the height of tabs. For the padding around tabs we'd need additional code that I'll add to the rounded tabs once I reupload it.

**Comment by dlc2001** [comment]
Great, thank you!  And yes to the best of my understanding I was using simple rounded tabs.

**Comment by Izheil** [comment]
I added it back as [Rounded-connected-tabs.as.css](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/blob/master/CSS%20tweaks/Tabs/Rounded-connected-tabs.as.css). 

Since it removes the padding around tabs, the tabs are more compact, and are similar to how they used to look before, but this also means that if you are using any of the scrollbale multirow versions, the max number of rows setting you used will be slightly misleading (since they mean stock Firefox rows), so for example 3 rows will be 4 rows and a part of another using rounded tabs.

You can manually edit multirow tabs file directly and change `--max-tab-rows` to some decimal number like 2.5, which should be 3 rows for the un-padded tabs on normal density. Overall they are around 0.83x the size of proton tabs.

**Comment by dlc2001** [comment]
Got it, works great, looks great, thank you!
