### ISSUE TITLE
[BUG] new tabs comes out in fullscreen

### ISSUE THREAD

**Issue by 532910** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#86]
Steps to reproduce:
0. Open a tab with a link
1. Enter full screen mode (F11)
2. Open link(s) in a new tab with a middle mouse click. Multiple times. As soon as a new row will be started you'll new tabs.

Expected behavior:
No tabs should be visible in fullscreen mode.

Debian sid FF81
MultiRowTabLiteforFx.uc.js is used

**Comment by Izheil** [comment]
Should be fixed in the [lastest version of the file](https://raw.githubusercontent.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/master/Multirow%20and%20other%20functions/Multirow%20tabs/MultiRowTabLiteforFx.uc.js).

**Comment by 532910** [comment]
I confirm it works fine now. Thank you!
