### ISSUE TITLE
[BUG] Installer on MacOS only works in Catalina (probably Mojave and Big Surprise as well) when SIP, System Integrity Protection, is disabled.  If SIP is not disabled, the Installer reports it could not complete because it had insufficient privileges.  Running in a Root shell had the same problem, only disabling SIP allowed the Installer to work on MacOS.

### ISSUE THREAD

**Issue by geekzer0** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#90]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior, or a brief explanation on it:

**Expected behavior**
A clear and concise description of what you expected to happen. Not needed for theming issues.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Linux]
 - Version [e.g. FF65, Nightly, ESR]

**Additional information**
Any information that could be relevant to fix the issue faster, such as:
 - You are using custom code that isn't in the default version contained in the repository.
 - Steps you followed to try to fix the issue on your own, if any.

**Comment by Izheil** [comment]
Not really a problem with the installer, but with how Apple walled their apps garden, so I can't do anything about it.

Either way, thanks for noting it, I'll add some notes on the installer for people having the same problem.

**Comment by geekzer0** [comment]
Thanks,

FYI disabling SIP works for some Macs, not all.  My iMacPro, that has an enhanced security module in the base offering, may be the reason.  I had to manually move the files in /Applications into place.  SIP was disabled (csrutil status displays it) but still just using touch /sbin/delete.me fails even with SIP disabled on that machine.  Bottom line – some hardware specific idiosyncrasies in that garden.

**Comment by Izheil** [comment]
> SIP was disabled (csrutil status displays it) but still just using touch /sbin/delete.me fails even with SIP disabled on that machine.

That sounds more like a problem with that specific hardware and configuration then, which again, is not something I can do anything about.

It's also something that is to be expected from running apps that don't come from the app store, since Apple only wants people to use the apps in there (Thus why the walled garden), and will by default try blocking people from using third party apps.
