### ISSUE TITLE
[BUG] Patcher doesn't work on macOS Catalina (tcl library not bundled)

### ISSUE THREAD

**Issue by phu54321** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#91]
**Describe the bug**
Patcher crashes because it couldn't find the required Tcl libraries.

**To Reproduce**
Steps to reproduce the behavior, or a brief explanation on it:
1. Install python3 with `brew install python3`. I know macOS bundles python3, but I had to install again with brew because it were dependency of `adoptopenjdk11`. I think this is a common practice for programmers.
2. Try running the patcher.

**Expected behavior**
It should show any GUI.

**Screenshots**
When the patcher is invoked via terminal (directly running `~~.app/Contents/MacOS/~~~~`, following error message is obtained.

```
Traceback (most recent call last):
  File "Builder.py", line 1850, in <module>
  File "Builder.py", line 1580, in UIStart
  File "tkinter/__init__.py", line 2261, in __init__
_tkinter.TclError: Can't find a usable init.tcl in the following directories: 
    /var/folders/1d/y4xjgfx53c9327jw9z7hs6lc0000gn/T/_MEItSD0f5/tcl /var/folders/1d/y4xjgfx53c9327jw9z7hs6lc0000gn/T/_MEItSD0f5/tcl8.6 /Library/Frameworks/Python.framework/Versions/3.8/lib/tcl8.6 /Users/whyask37/Desktop/Multirow-Patcher-Quantum-Nox-Installer.app/Contents/lib/tcl8.6 /Users/whyask37/Desktop/Multirow-Patcher-Quantum-Nox-Installer.app/lib/tcl8.6 /Users/whyask37/Desktop/Multirow-Patcher-Quantum-Nox-Installer.app/Contents/library /Users/whyask37/Desktop/Multirow-Patcher-Quantum-Nox-Installer.app/library /Users/whyask37/Desktop/Multirow-Patcher-Quantum-Nox-Installer.app/tcl8.6.8/library /Users/whyask37/Desktop/tcl8.6.8/library
```

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Version: FF v81, though not really important

**Additional information**

- Since the program requires exact version of Tcl library (8.6.10 according to current release), it would be best to bundle them.

**Comment by Izheil** [comment]
Tcl library is already bundled with the installer (as you can see in the MacOS.spec file used to generate the MacOS installer).
By default MacOS only comes with python2, not python3.

In Mac you don't even need to run the patcher from the terminal, if you want to run it directly with your python3 installation, download the files inside the `Multirow & other functions` folder of the repo, and run `python3 Quantum-Nox-Installer.py`.

**Comment by phu54321** [comment]
Ok. cloned the code and it worked :) thanks for the response
