### ISSUE TITLE
Arch linux installation fails

### ISSUE THREAD

**Issue by j-degreef** [Izheil/Quantum-Nox-Firefox-Dark-Full-Theme#95]
Installer fails on Archlinux

**To Reproduce**
Run the installer

**Expected behavior**
It installs.

**Desktop (please complete the following information):**
Archlinux up to date with i3 as WM
fontconfig-2:2.13.91+48+gfcb0420-2

`18:44:28 θ62° [jdegreef@nexus8:~/Downloads] $ sudo ./Multirow-Patcher-Quantum-Nox-Installer-Linux-1.7.8-rev2.elf 
Fontconfig warning: "/etc/fonts/fonts.conf", line 5: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/fonts.conf", line 6: unknown element "its:translateRule"
Fontconfig error: "/etc/fonts/fonts.conf", line 6: invalid attribute 'translate'
Fontconfig error: "/etc/fonts/fonts.conf", line 6: invalid attribute 'selector'
Fontconfig error: "/etc/fonts/fonts.conf", line 7: invalid attribute 'xmlns:its'
Fontconfig error: "/etc/fonts/fonts.conf", line 7: invalid attribute 'version'
Fontconfig warning: "/etc/fonts/fonts.conf", line 9: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/10-hinting-slight.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/20-unhint-small-vera.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/30-metric-aliases.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/45-generic.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/45-latin.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/49-sansserif.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/50-user.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/51-local.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/60-generic.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/60-latin.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/65-nonlatin.conf", line 4: unknown element "description"
Fontconfig error: Cannot load config file from /etc/fonts/fonts.conf
Traceback (most recent call last):
  File "Builder.py", line 1855, in <module>
  File "Builder.py", line 1592, in UIStart
  File "Builder.py", line 780, in __init__
  File "Builder.py", line 1299, in initUI
  File "tkinter/__init__.py", line 2766, in __init__
  File "tkinter/__init__.py", line 2299, in __init__
_tkinter.TclError: failed to allocate font due to internal system font engine problem
[485079] Failed to execute script Builder
`
Thanks for any help.

**Comment by Izheil** [comment]
Seems to be an issue with the configuration file of fontconfig and tkinter, not much that I can do about it.
Same as with [issue #85](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/issues/85), see if any of the fixes [here](https://bbs.archlinux.org/viewtopic.php?id=235643) help.

I can try updating python and tkinter to see if the new binary gets the fontconfig files right, but more than that I can't help much with it.

The only other alternative if none of that works will be to wait for the new version, on which I'll be using PySide2 because of the many issues of tkinter (tkinter seemed like the easiest way to get an installer going, but it was not the best long-term solution for it's many issues), but that will take me months, since I first have to finish the extension to manage all the scripts (which will be what the new installer will copy).

**Comment by Izheil** [comment]
I reuploaded [version 1.7.8](https://github.com/Izheil/Quantum-Nox-Firefox-Dark-Full-Theme/releases/download/FF82/Multirow-Patcher-Quantum-Nox-Installer-Linux-1.7.8-rev3.elf) with the lastest dependencies just in case. Try and see if that helps.

**Comment by j-degreef** [comment]
Great rev3 works ok.
It just says ""/etc/fonts/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"" but it doesn't seem to have any impact.

Thanks for your great works and to be so fast to reply.

**Comment by Izheil** [comment]
> It just says ""/etc/fonts/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"" but it doesn't seem to have any impact.

Thanks for letting me know! At least it works now, so I guess it was an issue with python or tkinter being a bit old on my end. 
I'll try to keep them in check with the lastest version compatible with pyinstaller next time.
